In [2]:
#1d array
import numpy as np
a=np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#2d array
b=np.arange(0,9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
#3d array
c=np.arange(0,12).reshape(3,2,2)
c

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [9]:
#to know the dimensions
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


In [12]:
marks=np.random.randint(0,100,20)
marks

array([46, 69, 36, 62, 32, 16, 47, 66, 32, 75,  1, 51, 30, 19, 56, 72, 53,
       48, 43, 51])

In [13]:
aes=np.sort(marks)
aes

array([ 1, 16, 19, 30, 32, 32, 36, 43, 46, 47, 48, 51, 51, 53, 56, 62, 66,
       69, 72, 75])

In [15]:
#deep copying
co=np.copy(aes)
co

array([ 1, 16, 19, 30, 32, 32, 36, 43, 46, 47, 48, 51, 51, 53, 56, 62, 66,
       69, 72, 75])

In [32]:
#
identity=np.eye(5).reshape(25)
identity


array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [29]:
identity=np.eye(5).flatten()
identity

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [33]:
identity=np.eye(5).ravel()
identity

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [37]:
np.ravel?

In [36]:
identity.flatten?

In [44]:
np.append(b,[[10,12,13]],axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 12, 13]])

In [49]:
np.eye(4)+4

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

In [52]:
farr=np.random.uniform(1,20,5)
farr

array([16.87109062,  8.45260041, 16.68195796,  9.44894467,  1.385275  ])

In [53]:
np.ceil(farr)

array([17.,  9., 17., 10.,  2.])

In [54]:
np.floor(farr)

array([16.,  8., 16.,  9.,  1.])

In [55]:
np.round(farr,decimals=3)

array([16.871,  8.453, 16.682,  9.449,  1.385])

In [59]:
mat=np.arange(0,25).reshape(5,5)
mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
np.min(mat)

0

In [61]:
np.max(mat)

24

In [66]:
np.std(mat)

7.211102550927978

In [73]:
null_vector=np.arange(0,11,dtype=float)
null_vector

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [74]:
null_vector[:]='NaN'
null_vector

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [75]:
null_vector[6]=200
null_vector

array([ nan,  nan,  nan,  nan,  nan,  nan, 200.,  nan,  nan,  nan,  nan])

In [78]:
#1d array vector
arr_vector=np.arange(100,151)
arr_vector

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [79]:
#To reverse an array
np.flip(arr_vector)

array([150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138,
       137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125,
       124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112,
       111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [84]:
#returns indices for a condtion
list=[1,0,2,0,0,4,0,8]
arr=np.array(list)
np.where(arr>0)

(array([0, 2, 5, 7], dtype=int64),)

In [89]:
n=np.ones(100).reshape(10,10)
n[1:9,1:9]=0
n

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [2]:
import numpy as np
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [5]:
np.random.uniform?

In [6]:
import numpy as np
list=[1,2,3]
np.array(list)

array([1, 2, 3])

array([[ 0.48333847, -1.14194702, -2.27149125, ..., -1.79027479,
         0.30063732,  1.36491752],
       [-0.01103913,  0.07967611,  0.36388846, ..., -0.99860759,
         0.5082063 ,  0.54000534],
       [ 0.05626909, -2.30364146, -0.90725016, ..., -0.63506598,
         1.14723593,  0.99226711],
       ...,
       [ 0.90360904,  0.1193478 , -0.50004973, ..., -0.42520664,
        -0.84445423,  0.58549333],
       [ 0.73541224, -1.17924104,  0.90628565, ..., -0.03615473,
        -0.57787768,  0.7223086 ],
       [ 0.53508124,  0.1898605 ,  1.07568372, ...,  1.3009618 ,
        -1.19174225, -0.07695852]])